sh scripts/1-keyering.sh
sh scripts/2-paru.sh
sh scripts/3-pipewire.sh
sh scripts/4-zsh.sh
sh scripts/5-packages.sh
sh scripts/6-codium.sh
sh scripts/7-jabba.sh
sh scripts/8-node.sh
sh scripts/9-partitions.sh
